version: "3"
services:
  # Next.jsの環境
  view:
    container_name: "view"
    build:
      context: ./view
      dockerfile: view.Dockerfile
    volumes:
      - ./view:/view
      - ./view/node_modules:/view/node_modules
    command: sh -c "yarn && yarn dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9004
    env_file:
      - ./view.env

  #フロントとバックの通信(FastAPI)の環境
  api:
    container_name: FastAPI
    build:
      context: ./api
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "9004:9004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    environment:
      - ACSESS_ALLOW_URL=http://localhost:3000
    env_file:
      - ./api.env
